name: Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile

      - name: vitest
        run: yarn run vitest --run

      - name: build
        run: yarn run build

      - name: dry-publish
        run: npm publish --provenance --dry-run
