name: Publish Package to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4 # npm is required for provenance support
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile

      # make sure this publish doesn’t break anything
      - run: bun run test

      - run: bun run build

      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
